apiVersion: v1
kind: ConfigMap
metadata:
  name: fbis-ccf-configmap
  namespace: {{ .KUBE_NAMESPACE }}
  labels:
    name: fbis-ccf
data:
  ENVIRONMENT: "DEV"
  COMMIT_SHA: {{ .DRONE_COMMIT_SHA }}
  GA_ID: "UA-999999-1"
  NODE_ENV: "development"
  TEMPLATE_QUERY: "f74ed86d-6d95-4e4a-88c8-b9875ed69b12"
  TEMPLATE_FEEDBACK: "837dc8ac-6abf-4f6a-9f0c-57a28ea7f43c"
