pipeline:

  unit_test:
    image: node
    commands:
      - npm install
      - npm test
    when:
      event: push
      branch: [ master, development ]

  build:
    image: docker:17.09.0-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t sas/fbis-ccf:$${DRONE_BUILD_NUMBER} .
    when:
      event: push
      branch: [ master, development ]

  scan:
    image: quay.io/ukhomeofficedigital/anchore-submission:latest
    dockerfile: ./Dockerfile
    image_name: sas/fbis-ccf:${DRONE_BUILD_NUMBER}
    local_image: true
    tolerate: medium
    #whitelist: CVE_SOMENAME_1,CVE_SOMENAME_2
    #whitelist_file: <PATH>
    show_all_vulnerabilities: true
    fail_on_detection: false
    when:
      event: push
      branch: [ master, development ]

  create_artefact:
    image: quay.io/ukhomeofficedigital/ecr:latest
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    repo: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/sas/fbis-ccf
    tags:
      - latest_${DRONE_BRANCH}
      - ${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: [ master, development ]

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    secrets:
      - kube_token_fbis_acp_notprod
    environment:
      - KUBE_NAMESPACE=sas-fbis-dev
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    commands:
      - export KUBE_TOKEN=$${KUBE_TOKEN_FBIS_ACP_NOTPROD}
      - kd --insecure-skip-tls-verify --check-interval 10s -f kube/redis-service.yml -f kube/redis-network-policy.yml -f kube/redis-deployment.yml
      - kd --insecure-skip-tls-verify -f kube/dev/configmap.yaml -f kube/dev/ingress-internal.yaml -f kube/networkpolicy-internal.yaml -f kube/service.yaml
      - kd --insecure-skip-tls-verify --timeout 10m --check-interval 10s -f kube/dev/deployment.yaml
    when:
      event: push
      branch: master

  deploy_to_branch:
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    secrets:
      - kube_token_fbis_acp_notprod
    environment:
      - KUBE_NAMESPACE=sas-fbis-branch
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    commands:
      - export KUBE_TOKEN=$${KUBE_TOKEN_FBIS_ACP_NOTPROD}
      - kd --insecure-skip-tls-verify --check-interval 10s -f kube/redis-service.yml -f kube/redis-network-policy.yml -f kube/redis-deployment.yml
      - kd --insecure-skip-tls-verify -f kube/branch/configmap.yaml -f kube/branch/ingress-internal.yaml -f kube/networkpolicy-internal.yaml -f kube/service.yaml
      - kd --insecure-skip-tls-verify --timeout 10m --check-interval 10s -f kube/branch/deployment.yaml
    when:
      event: push
      branch: development

  deploy_to_uat:
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    secrets:
      - kube_token_fbis_acp_notprod
    environment:
      - KUBE_NAMESPACE=sas-fbis-uat
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    commands:
      - export KUBE_TOKEN=$${KUBE_TOKEN_fbis_ACP_NOTPROD}
      - kd --insecure-skip-tls-verify --check-interval 10s -f kube/redis-service.yml -f kube/redis-network-policy.yml -f kube/redis-deployment.yml
      - kd --insecure-skip-tls-verify -f kube/uat/configmap.yaml -f kube/uat/ingress-internal.yaml -f kube/networkpolicy-internal.yaml -f kube/service.yaml
      - kd --insecure-skip-tls-verify --timeout 10m --check-interval 10s -f kube/uat/deployment.yaml
    when:
      environment: UAT
      event: deployment

  deploy_to_stg:
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    secrets:
      - kube_token_fbis_acp_prod
    environment:
      - KUBE_NAMESPACE=sas-fbis-stg
      - KUBE_SERVER=https://kube-api-prod.prod.acp.homeoffice.gov.uk
    commands:
      - export KUBE_TOKEN=$${KUBE_TOKEN_FBIS_ACP_PROD}
      - kd --insecure-skip-tls-verify --check-interval 10s -f kube/redis-service.yml -f kube/redis-network-policy.yml -f kube/redis-deployment.yml
      - kd --insecure-skip-tls-verify -f kube/stg/configmap.yaml -f kube/stg/ingress-internal.yaml -f kube/networkpolicy-internal.yaml -f kube/service.yaml
      - kd --insecure-skip-tls-verify --timeout 10m --check-interval 10s -f kube/stg/deployment.yaml
    when:
      environment: STG
      event: deployment

  deploy_to_prod:
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    secrets:
      - kube_token_fbis_acp_prod
    environment:
      - KUBE_NAMESPACE=sas-fbis-prod
      - KUBE_SERVER=https://kube-api-prod.prod.acp.homeoffice.gov.uk
    commands:
      - export KUBE_TOKEN=$${KUBE_TOKEN_FBIS_ACP_PROD}
      - kd --insecure-skip-tls-verify --check-interval 10s -f kube/redis-service.yml -f kube/redis-network-policy.yml -f kube/redis-deployment.yml
      - kd --insecure-skip-tls-verify -f kube/prod/configmap.yaml -f kube/prod/ingress-external.yaml -f kube/networkpolicy-external.yaml -f kube/service.yaml
      - kd --insecure-skip-tls-verify --timeout 10m --check-interval 10s -f kube/prod/deployment.yaml
    when:
      environment: PROD
      event: deployment

  manual_deploy_to_branch:
    image: quay.io/ukhomeofficedigital/kd:v1.14.0
    secrets:
      - kube_token_fbis_acp_notprod
    environment:
      - KUBE_NAMESPACE=sas-fbis-branch
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    commands:
      - export KUBE_TOKEN=$${KUBE_TOKEN_FBIS_ACP_NOTPROD}
      - kd --insecure-skip-tls-verify --check-interval 10s -f kube/redis-service.yml -f kube/redis-network-policy.yml -f kube/redis-deployment.yml
      - kd --insecure-skip-tls-verify -f kube/branch/configmap.yaml -f kube/branch/ingress-internal.yaml -f kube/networkpolicy-internal.yaml -f kube/service.yaml
      - kd --insecure-skip-tls-verify --timeout 10m --check-interval 10s -f kube/branch/deployment.yaml
    when:
      environment: BRANCH
      event: deployment

  sonar-scanner:
    image: quay.io/ukhomeofficedigital/sonar-scanner-node:latest
    failure: ignore
    when:
      event: push
      branch: master

  notify_slack_build:
    image: plugins/slack:1.1
    failure: ignore
    secrets:
      - SLACK_WEBHOOK
    channel: refugee-integration-loan-build
    username: Drone
    icon_url: http://readme.drone.io/0.5/logo_dark.svg
    icon.url: http://readme.drone.io/0.5/logo_dark.svg
    template: >
      BUILD on {{build.event}} of FBIS has {{build.status}} - <{{build.link}}|#{{build.number}}>
      {{#success build.status}}
        :thumbsup: :thumbsup: :thumbsup:
      {{else}}
        :x: :x: :x:
      {{/success}}
      Author: {{build.author}}


      Duration: {{since job.started}}\n


      Job: <{{build.link}}|#{{build.number}}>\n


      Commit: {{build.commit}}
    when:
      branch: master
      event: push

  notify_slack_deploy:
    image: plugins/slack:1.1
    failure: ignore
    secrets:
      - SLACK_WEBHOOK
    channel: refugee-integration-loan-build
    username: Drone
    icon_url: http://readme.drone.io/0.5/logo_dark.svg
    icon.url: http://readme.drone.io/0.5/logo_dark.svg
    template: >
      DEPLOY to {{deploy.to}} of FBIS has {{build.status}} - <{{build.link}}|#{{build.number}}>
      {{#success build.status}}
        :thumbsup: :thumbsup: :thumbsup:
      {{else}}
        :x: :x: :x:
      {{/success}}
      Author: {{build.author}}


      Duration: {{since job.started}}


      Job: <{{build.link}}|#{{build.number}}>


      Commit: {{build.commit}}
    when:
      event: deployment
