apiVersion: v1
kind: ConfigMap
metadata:
  name: fbis-ccf-configmap
  namespace: {{ .KUBE_NAMESPACE }}
  labels:
    name: fbis-ccf
data:
  ENVIRONMENT: "DEV"
  COMMIT_SHA: {{ .DRONE_COMMIT_SHA }}
  GA_ID: "UA-999999-1"
  NODE_ENV: "development"
