apiVersion: v1
kind: ConfigMap
metadata:
  name: fbis-ccf-configmap
  namespace: {{ .KUBE_NAMESPACE }}
  labels:
    name: fbis-ccf
data:
  ENVIRONMENT: "STG"
  COMMIT_SHA: {{ .DRONE_COMMIT_SHA }}
  GA_ID: "UA-666666-1"
  NODE_ENV: "production"
  TEMPLATE_QUERY: "c46a8521-7330-41a5-8afd-9e175a5c8360"
  TEMPLATE_FEEDBACK: "c215bef5-553a-4fe0-9d2d-379f4a695f05"
