apiVersion: v1
kind: ConfigMap
metadata:
  name: fbis-ccf-configmap
  namespace: {{ .KUBE_NAMESPACE }}
  labels:
    name: fbis-ccf
data:
  ENVIRONMENT: "PROD"
  COMMIT_SHA: {{ .DRONE_COMMIT_SHA }}
  GA_ID: "UA-666666-1"
  NODE_ENV: "production"
  TEMPLATE_QUERY: "f74ed86d-6d95-4e4a-88c8-b9875ed69b12"
