---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fbis-ccf-external
  labels:
    cert-manager.io/solver: http01
  annotations:
    cert-manager.io/enabled: "true"
    ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingress.kubernetes.io/session-cookie-name: ingress
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx-external
spec:
  tls:
    - hosts:
        - immigration-account-help.homeoffice.gov.uk
      secretName: fbis-ccf-external
  rules:
    - host: immigration-account-help.homeoffice.gov.uk
      http:
        paths:
          - path: /
            backend:
              serviceName: fbis-ccf
              servicePort: 443
